### ISSUE TITLE
Have you tried pretraining with the multi-parallel data?

### ISSUE THREAD

**Issue by frankang** [research-anonymous/MultiParallelFinetuning4MMT#1]
Did you try adding some multi-parallel data with the english-centric data in the pretraining stage? (Then followed by the same finetuning stage)
I think this may encourage the model to learn some multi-to-multi characteristics during pretraining.

**Comment by moore3930** [comment]
Hi, thanks for your question. Yes, we tried and the impact is minimal. It is also intuitive since in training time the few non-English data (multi-parallel) will be washed out by the large amount of English-centric bitext.

**Comment by frankang** [comment]
Thanks!
